/**
 * reportWebVitals
 *
 * Used to measure performance metrics in the application.
 * This file is typically generated by Create React App.
 *
 * It dynamically imports the "web-vitals" library
 * only when a performance tracking function is provided.
 */

const reportWebVitals = (onPerfEntry) => {

  /**
   * Ensure the argument passed is a valid function.
   * This prevents errors if nothing is provided.
   */
  if (onPerfEntry && onPerfEntry instanceof Function) {

    /**
     * Dynamically import web-vitals to avoid increasing
     * bundle size unless performance tracking is needed.
     *
     * This is called "code splitting".
     */
    import('web-vitals').then(
      ({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {

        /**
         * Each function measures a specific performance metric:
         *
         * CLS  → Cumulative Layout Shift
         * FID  → First Input Delay
         * FCP  → First Contentful Paint
         * LCP  → Largest Contentful Paint
         * TTFB → Time To First Byte
         */

        getCLS(onPerfEntry);
        getFID(onPerfEntry);
        getFCP(onPerfEntry);
        getLCP(onPerfEntry);
        getTTFB(onPerfEntry);
      }
    );
  }
};

/**
 * Export the function so it can be used in index.js
 * Example usage:
 *
 * reportWebVitals(console.log);
 *
 * Or send metrics to an analytics endpoint.
 */
export default reportWebVitals;
